# Generated by Django 6.1.1 on 2026-10-04 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('categoria', models.CharField(choices=[('CONSOLAS', 'Consolas'), ('NOTEBOOKS', 'Notebooks'), ('ESCRITORIO', 'Computadores de escritorio'), ('COMPONENTES', 'Componentes'), ('PERIFERICOS', 'Periféricos')], default='CONSOLAS', max_length=20, verbose_name='categoría')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio (CLP)')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock')),
                ('descripcion', models.TextField(verbose_name='descripción técnica')),
                ('estado', models.BooleanField(choices=[(True, 'Disponible'), (False, 'Agotado')], default=True, verbose_name='estado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
